package network.ermis.core.models

import androidx.compose.runtime.Immutable

/**
 * Device's information needed to register push notifications.
 *
 * @property token Device's token generated by push notification provider.
 * @property pushProvider Push notifications provider type.
 * @property providerName Push notifications provider name.
 * @see [PushProvider]
 */
@Immutable
public data class Device(
    val token: String,
    val pushProvider: PushProvider,
    val providerName: String?,
)

/**
 * Push notifications provider type.
 */
public enum class PushProvider(public val key: String) {
    /** Firebase push notification provider */
    FIREBASE("firebase"),

    /** Huawei push notification provider */
    HUAWEI("huawei"),

    /** Xiaomi push notification provider */
    XIAOMI("xiaomi"),

    /** Unknown push notification provider */
    UNKNOWN("unknown"),
    ;

    public companion object {
        public fun fromKey(key: String): PushProvider =
            values().firstOrNull { it.key == key } ?: UNKNOWN
    }
}
